### PR TITLE
Add shared ESLint configuration and tsconfig

### PR DESCRIPTION
**Pull request by snoack**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/reviewable-configs/1)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
Looks good overall — some of the questions are mainly for my own education.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-:-O7gl5_ZB8Pzkw3IBg4d:b-q3wi9t)* status: all files reviewed, 4 unresolved discussions (waiting on @snoack)

___
*[`LICENSE` line 3 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7ghwb417j0yfJr-DPY:-O7ghwb417j0yfJr-DPZ:b-gjxji4) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/LICENSE#L3)):*
> ```
> The MIT License (MIT)
> 
> Copyright (c) 2024 Piotr Kaminski
> ```

Might as well use "Ideanest LLC" here.  I should probably update all our other licenses as well.
___
*[`tsconfig.json` line 2 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7gj-FGBuJq4YbEXMcS:-O7gj-FGBuJq4YbEXMcT:b-zgipct) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/tsconfig.json#L2)):*
> ```jsonc
> {
>     "compilerOptions": {
> ```

Any reason not to include `forceConsistentCasingInFileNames: true`?
___
*[`tsconfig.json` line 6 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7gjHtpBMcyTNxfVh1z:-O7gjHtpBMcyTNxfVh2-:b-orq9k5) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/tsconfig.json#L6)):*
> ```jsonc
>         "esModuleInterop": true,
>         "resolveJsonModule": true,
>         "module": "commonjs",
> ```

I wonder if we should switch to `ESNext` modules throughout, now that Node has gotten with the program?  Probably too much to deal with right now, though.
___
*[`eslint-config/_configs/typescript.js` line 5 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7gkoXQE871YpZPm6JD:-O7gkoXQE871YpZPm6JE:b-tefr9y) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/eslint-config/_configs/typescript.js#L5)):*
> ```JavaScript
> 
> export default [
>   ...typescript.configs.recommended,
> ```

There used to be two separate configs to inherit from (`@typescript-eslint/eslint-recommended` and `@typescript-eslint/recommended`), did that change with the flat configs?
___
*[`eslint-config/_configs/typescript.js` line 11 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7gkWRr4NiOQMLkWbZ4:-O7gkWRr4NiOQMLkWbZ5:b-whyssu) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/eslint-config/_configs/typescript.js#L11)):*
> ```JavaScript
>       '@typescript-eslint/no-floating-promises': 'error',
>       '@typescript-eslint/no-misused-promises': 'error',
>       '@typescript-eslint/no-unused-vars': ['error', {args: 'none', varsIgnorePattern: '^unused'}],
> ```

Don't we need to turn off the baseline `no-unused-vars` to avoid false positives?  Or does the new flat config magically take care of that for us somehow?

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`LICENSE` line 3 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7ghwb417j0yfJr-DPY:-O7iS6ol0MN9eehu2P7z:b-896fix) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/LICENSE#L3)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Might as well use "Ideanest LLC" here.  I should probably update all our other licenses as well.
</blockquote></details>

Done.
___
*[`tsconfig.json` line 2 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7gj-FGBuJq4YbEXMcS:-O7i8wQ26GbSONzWzjmU:bk6t8a4) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/tsconfig.json#L2)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Any reason not to include `forceConsistentCasingInFileNames: true`?
</blockquote></details>

It's `true` by default.
___
*[`tsconfig.json` line 6 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7gjHtpBMcyTNxfVh1z:-O7iVIl_7s_IydUUvZ7_:b-w5paw6) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/tsconfig.json#L6)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I wonder if we should switch to `ESNext` modules throughout, now that Node has gotten with the program?  Probably too much to deal with right now, though.
</blockquote></details>

Not as part of the migration to a shared config I'd say. Lets keep the changes affecting the build output minimal here. I filed a separate issue: Reviewable/reviewable-configs#2
___
*[`eslint-config/_configs/typescript.js` line 5 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7gkoXQE871YpZPm6JD:-O7i9Msp547g6x8zAiiv:b-y2z0vt) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/eslint-config/_configs/typescript.js#L5)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

There used to be two separate configs to inherit from (`@typescript-eslint/eslint-recommended` and `@typescript-eslint/recommended`), did that change with the flat configs?
</blockquote></details>

`eslintRecommended` is included in `recommended`.
___
*[`eslint-config/_configs/typescript.js` line 11 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7gkWRr4NiOQMLkWbZ4:-O7iBo-SBR_dO0jh9m96:b-7ctrh8) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/eslint-config/_configs/typescript.js#L11)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Don't we need to turn off the baseline `no-unused-vars` to avoid false positives?  Or does the new flat config magically take care of that for us somehow?
</blockquote></details>

`'no-unused-vars': 'off'` is already included in`typescript-eslint`'s `recommended` config.

**Review by pkaminski — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-:-O7jtClG4tFIK29ov6Iw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

___
*[`package.json` line 7 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7lpBel5Hdf66_EGF5w:-O7lpBel5Hdf66_EGF5x:bpc1l6k) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/package.json#L7)):*
> ```JSON
>   "license": "MIT",
>   "type": "module",
>   "exports": {
> ```

I'm curious what necessitated removing the exports and switching to raw config imports?

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

___
*[`package.json` line 7 at r1](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7lpBel5Hdf66_EGF5w:-O7lpeNjD2dYodQNc83P:b-4m40hr) ([raw file](https://github.com/reviewable/reviewable-configs/blob/00d3a238b1949fed4ff21edb01b419da912ee0a0/package.json#L7)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I'm curious what necessitated removing the exports and switching to raw config imports?
</blockquote></details>

The purpose of the previous `exports` declaration was so that I can import `reviewable-confgis/eslint-config` instead of having to type out `reviewable-confgis/eslint-config/index.js`. By default all files are exported with their original path within the package.

I removed the aggregation module (i.e. `index.js`), hence making the exports declaration redundant, because the ESM implementation in Node.js isn't as smart as I thought it is. Apparently, no matter which of the named exports you import it's going to import all modules referenced in the aggregation module first. That means even if you only import the `baseline` and `lodash` configs it still imports the `typescript` config internally which causes an error in `reviewable-client` where we don't have the `typescript` package installed.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`eslint-config/baseline.js` line 9 at r5](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7q4mqcC2UHr7x6_XYh:-O7q4mqcC2UHr7x6_XYi:b-yqunos) ([raw file](https://github.com/reviewable/reviewable-configs/blob/105e27dbe4882f6406c85eab6df8df9d9b03e990/eslint-config/baseline.js#L9)):*
> ```JavaScript
>   {
>     languageOptions: {
>       ecmaVersion: 2022
> ```

This might be too aggressive for the client.  Thoughts @earlAchromatic?

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1)* status: all files reviewed, 1 unresolved discussion (waiting on @earlAchromatic)

___
*[`eslint-config/baseline.js` line 9 at r5](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7q4mqcC2UHr7x6_XYh:-O7q6GpFBrbawDKTMO4O:b-i0f4tq) ([raw file](https://github.com/reviewable/reviewable-configs/blob/105e27dbe4882f6406c85eab6df8df9d9b03e990/eslint-config/baseline.js#L9)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

This might be too aggressive for the client.  Thoughts @earlAchromatic?
</blockquote></details>

This is not meant for the client. This option is overridden for the client code. We basically only fall back to this default for code that runs on Node.js (including the build tooling for the client).

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1)* status: all files reviewed, 1 unresolved discussion (waiting on @earlAchromatic)

___
*[`eslint-config/baseline.js` line 9 at r5](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7q4mqcC2UHr7x6_XYh:-O7q72FE4zqeWY4pdUc8:b9149mq) ([raw file](https://github.com/reviewable/reviewable-configs/blob/105e27dbe4882f6406c85eab6df8df9d9b03e990/eslint-config/baseline.js#L9)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

This is not meant for the client. This option is overridden for the client code. We basically only fall back to this default for code that runs on Node.js (including the build tooling for the client).
</blockquote></details>

Hmm, then I think I'll re-up my suggestion of having `config-browser`, `config-node` and `config-isomorphic`, otherwise it requires downstream consumers to know too much about the details of which configs to use and what properties to override.

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1)* status: all files reviewed, 1 unresolved discussion (waiting on @earlAchromatic)

___
*[`eslint-config/baseline.js` line 9 at r5](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7q4mqcC2UHr7x6_XYh:-O7q9dDI4ymVH4IQiT23:b-rotypi) ([raw file](https://github.com/reviewable/reviewable-configs/blob/105e27dbe4882f6406c85eab6df8df9d9b03e990/eslint-config/baseline.js#L9)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Hmm, then I think I'll re-up my suggestion of having `config-browser`, `config-node` and `config-isomorphic`, otherwise it requires downstream consumers to know too much about the details of which configs to use and what properties to override.
</blockquote></details>

Both `reviewable-client` and `hubkit` were already overriding the `ecmaVersion` before I even implemented this default in the baseline config. BTW, without setting `ecmaVersion` here it defaults to 2018 as this is what the `eslint-plugin-import` sets it to. So if anything this is more explicit. Finally, implementing those presets you are suggesting just makes things more complicated, increasing the boilerplate. Note that even `reviewable-client` has code as part of its tooling that runs on Node.js and requires a fairly recent `ecmaVersion`to be set. So the `eslint.config.mjs` in `reviewable-client` would have to use both `config-browser` and `config-node` and wrap them in some pattern like `[...].map(config => {files: [...], ...config})`.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1)* status: all files reviewed, 1 unresolved discussion (waiting on @earlAchromatic)

___
*[`eslint-config/baseline.js` line 9 at r5](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7q4mqcC2UHr7x6_XYh:-O7qcM_j0njNw3G28k-_:bvh10pj) ([raw file](https://github.com/reviewable/reviewable-configs/blob/105e27dbe4882f6406c85eab6df8df9d9b03e990/eslint-config/baseline.js#L9)):*
> So if anything this is more explicit

Explicit is good (and why would a plugin set a default for this!?) but it would be better if we could set the right version for all client-side code rather than override it in each downstream project.  All our client code is intended to run in the same environment, after all.

> So the `eslint.config.mjs` in `reviewable-client` would have to use both `config-browser` and `config-node`

Since the target environment varies by directory tree, would it be simpler to add separate `eslint.config.mjs` files in the relevant subdirectories with a simple `config-node-js` or `config-node-ts` configuration?  I assume ESLint uses the nearest file even with flat configs, and doesn't implicitly inherit once the nearest file is found.

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1)* status: all files reviewed, 1 unresolved discussion (waiting on @earlAchromatic)

___
*[`eslint-config/baseline.js` line 9 at r5](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7q4mqcC2UHr7x6_XYh:-O7qjqPn7V_wPxd3dJFI:bislyla) ([raw file](https://github.com/reviewable/reviewable-configs/blob/105e27dbe4882f6406c85eab6df8df9d9b03e990/eslint-config/baseline.js#L9)):*
> All our client code is intended to run in the same environment, after all.

In practice there are only two projects we have that target the browser, or rather one project targeting the browser only, and one "isomorphic" project.

Also while there is probably no reason to support ES5 with `hubkit` anymore, there might be a case for a library that might be used by others to be a bit more conservative regarding support of legacy environments. And even if we don't care about other potential users of the library it doesn't seem to be a priority to modernize that code.

I'd say let think about better ways to abstract things once we have 3 projects that share enough requirements. The only case where we actually have a common platform is the code that is running on Node.js only, since we have some of this code in every single repo.

> Since the target environment varies by directory tree,

Actually, in case of `reviewable-client` it's more complex, i.e. everything in the `build` subdirectory targets Node.js except for the scripts with `_prelude.js` suffix. Then there are also a couple scripts targeting Node.js on the top-level, i.e. `Gruntfile.js` and `eslint.config.mjs`. So it's not cleanly separated by directory at all.

> would it be simpler to add separate `eslint.config.mjs` files in the relevant subdirectories

The "flat" in Flat configs is descriptive for no longer having multiple config files scattered through the directory tree, but to flatten the configuration into one file. So that won't work unless you want to call `eslint` separately for each config file.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable-configs/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

___
*[`eslint-config/baseline.js` line 9 at r5](https://reviewable.io/reviews/reviewable/reviewable-configs/1#-O7q4mqcC2UHr7x6_XYh:-O7rL8YxA4zR9ooCUzRf:b-k3q2e4) ([raw file](https://github.com/reviewable/reviewable-configs/blob/105e27dbe4882f6406c85eab6df8df9d9b03e990/eslint-config/baseline.js#L9)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

> All our client code is intended to run in the same environment, after all.

In practice there are only two projects we have that target the browser, or rather one project targeting the browser only, and one "isomorphic" project.

Also while there is probably no reason to support ES5 with `hubkit` anymore, there might be a case for a library that might be used by others to be a bit more conservative regarding support of legacy environments. And even if we don't care about other potential users of the library it doesn't seem to be a priority to modernize that code.

I'd say let think about better ways to abstract things once we have 3 projects that share enough requirements. The only case where we actually have a common platform is the code that is running on Node.js only, since we have some of this code in every single repo.

> Since the target environment varies by directory tree,

Actually, in case of `reviewable-client` it's more complex, i.e. everything in the `build` subdirectory targets Node.js except for the scripts with `_prelude.js` suffix. Then there are also a couple scripts targeting Node.js on the top-level, i.e. `Gruntfile.js` and `eslint.config.mjs`. So it's not cleanly separated by directory at all.

> would it be simpler to add separate `eslint.config.mjs` files in the relevant subdirectories

The "flat" in Flat configs is descriptive for no longer having multiple config files scattered through the directory tree, but to flatten the configuration into one file. So that won't work unless you want to call `eslint` separately for each config file.
</blockquote></details>

Fair enough — I've learned a few things.

Regarding mixed-config directories, we can easily split the files up into separate directories if it would be more convenient.  (Even nicer would be if we could define named config sets and have a file opt into one of them via a comment directive.)  The multitude of file inclusions/exclusions feels a bit brittle — it'll be easy to forget to update those lists when adding a new file.

As for legacy browser environments, I feel like we're conservative enough for our main one that we don't need to make allowances for older ones.  There's been no salient reason to modernize `hubkit` so far, but if it would simplify the ESLint config then it's definitely something we could do.

**Pull request merged**
